### PR TITLE
Update to Go 1.16.9 and bump joes2go

### PR DESCRIPTION
**Pull request by xinfengliu**
Signed-off-by: Xinfeng Liu <xinfeng.liu@gmail.com>

- Update to Go 1.16.9 
- Bump joes2go (fixes https://github.com/notaryproject/notary/issues/1602)
- Update certs in `fixtures/rethinkdb` to avoid cert errors in integration test.

### CODE REVIEW

**Comment by stefan-zh** [comment]
Can one of the maintainers look into this PR? Notary runs Go `1.14`, which is already [end of life](https://endoflife.date/go) and it makes sense to upgrade.
@justincormack @thaJeztah @marcofranssen

**Comment by marcofranssen** [comment]
> Can one of the maintainers look into this PR? Notary runs Go `1.14`, which is already [end of life](https://endoflife.date/go) and it makes sense to upgrade. @justincormack @thaJeztah @marcofranssen

Sorry not a maintainer, but would indeed be great to bump.

**Review by justincormack — APPROVED** [review]

**Comment by stefan-zh** [comment]
Thanks @justincormack . I see from the Contribution Rules that 2 maintainers are required for a merge. @HuKeping could you please check if this PR looks good to you?

**Review by HuKeping — APPROVED** [review]

**Review by HuKeping — APPROVED** [review]

**Comment by stefan-zh** [comment]
Thanks @HuKeping ! I tested the change in this pull request at my job and it works fine. @justincormack could you merge it into `master`? Thanks!

**Review by HuKeping — APPROVED** [review]

**Pull request merged**
