### PR TITLE
Update to Go 1.15.7

### PR DESCRIPTION
**Pull request by thaJeztah**
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, fun; looks like it won't work with Go 1.15;

```
server_1_8b2786804982 | {"level":"fatal","msg":"Error starting rethinkdb driver: rethinkdb: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0","time":"2021-01-26T09:43:58Z"}
rdb-proxy_1_1bee00b8fa44 | warn: Driver connection TLS handshake failed: sslv3 alert bad certificate (OpenSSL error 336151570)
```

Relates to https://github.com/golang/go/issues/39568

**Comment by HuKeping** [comment]
Seems like we should re-generate the fixture certs with SAN first? 

Anyway I'll get it.

**Comment by stefan-zh** [comment]
What is the status of this pull request? Also, why is the version not bumped in `go.mod`? https://github.com/theupdateframework/notary/blob/master/go.mod#L3

**Comment by stefan-zh** [comment]
This pull request has been superseded by https://github.com/notaryproject/notary/pull/1616 @thaJeztah @justincormack I guess this PR be closed now

**Pull request closed without merging**
